version: "3.8"
services:
  app:
    build: .
    container_name: express-app-om
    ports:
      - "5001:5000"
    environment:
      PORT: 5000
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    restart: always
    volumes:
      - "C:\\Users\\rafiu\\OneDrive\\Desktop\\My_Resources\\My_Files\\Learning_Dev_Resources\\Courses\\Backend Engineering - Poridhi\\Projects\\manush-tech-task\\order-management-backend:/usr/src/app"
      - "/usr/src/app/node_modules"

  db:
    image: postgres:latest
    container_name: posgress-om
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
